INSERT INTO pets (name, age, type, breed, microchip) VALUES('Jonathan', 6, 'dog', 'Glen of Imaal Terrier', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Nakia', 14, 'dog', 'Glen of Imaal Terrier', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Lori', 5, 'dog', 'Glen of Imaal Terrier', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Donny', 13, 'dog', 'Glen of Imaal Terrier', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Ladarius', 18, 'dog', 'Glen of Imaal Terrier', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Everette', 20, 'dog', 'Glen of Imaal Terrier', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Clare', 19, 'dog', 'Perro de Pastor Mallorquin', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Erik', 16, 'dog', 'Perro de Pastor Mallorquin', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Corene', 8, 'dog', 'Perro de Pastor Mallorquin', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Valerie', 8, 'dog', 'Perro de Pastor Mallorquin', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Lenora', 3, 'dog', 'Perro de Pastor Mallorquin', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Larue', 16, 'dog', 'Perro de Pastor Mallorquin', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Carroll', 17, 'dog', 'Perro de Pastor Mallorquin', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Milford', 13, 'dog', 'Grand Griffon Vendéen', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Karine', 10, 'dog', 'Grand Griffon Vendéen', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Asha', 4, 'dog', 'Grand Griffon Vendéen', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Garth', 5, 'dog', 'Grand Griffon Vendéen', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Davin', 8, 'dog', 'Grand Griffon Vendéen', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Kelley', 2, 'dog', 'Grand Griffon Vendéen', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Lexi', 9, 'dog', 'Grand Griffon Vendéen', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Bethany', 16, 'dog', 'Grand Griffon Vendéen', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Yessenia', 4, 'dog', 'Grand Griffon Vendéen', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Hope', 10, 'dog', 'Grand Griffon Vendéen', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Brock', 3, 'dog', 'Grand Griffon Vendéen', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Ewald', 7, 'dog', 'Grand Griffon Vendéen', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Jeffry', 17, 'dog', 'Drentse Patrijshond', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Kaley', 18, 'dog', 'Drentse Patrijshond', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Kennith', 15, 'dog', 'Drentse Patrijshond', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Dave', 7, 'dog', 'Drentse Patrijshond', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Charlene', 1, 'dog', 'Drentse Patrijshond', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Maia', 19, 'dog', 'Drentse Patrijshond', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Yesenia', 8, 'dog', 'Drentse Patrijshond', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Keara', 10, 'dog', 'Drentse Patrijshond', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Garth', 2, 'dog', 'Drentse Patrijshond', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Meredith', 1, 'dog', 'Drentse Patrijshond', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Genevieve', 18, 'dog', 'Drentse Patrijshond', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Kathryne', 9, 'dog', 'Drentse Patrijshond', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Jessy', 6, 'dog', 'Drentse Patrijshond', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Olga', 19, 'dog', 'Australian Stumpy Tail Cattle Dog', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Jess', 11, 'dog', 'Australian Stumpy Tail Cattle Dog', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Reese', 9, 'dog', 'Australian Stumpy Tail Cattle Dog', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Meda', 17, 'dog', 'Australian Stumpy Tail Cattle Dog', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Nyasia', 2, 'dog', 'Australian Stumpy Tail Cattle Dog', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Merle', 18, 'dog', 'Australian Stumpy Tail Cattle Dog', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Hosea', 16, 'dog', 'Australian Stumpy Tail Cattle Dog', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Estrella', 18, 'dog', 'Australian Stumpy Tail Cattle Dog', true);        
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Camilla', 14, 'dog', 'Australian Stumpy Tail Cattle Dog', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Laila', 11, 'dog', 'Australian Stumpy Tail Cattle Dog', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Lucius', 17, 'dog', 'Australian Stumpy Tail Cattle Dog', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Darren', 14, 'dog', 'Australian Stumpy Tail Cattle Dog', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Ole', 12, 'dog', 'Australian Stumpy Tail Cattle Dog', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Afton', 8, 'dog', 'Australian Stumpy Tail Cattle Dog', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Coy', 6, 'dog', 'Cane Paratore', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('London', 9, 'dog', 'Cane Paratore', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Salvatore', 5, 'dog', 'Cane Paratore', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Angelo', 4, 'dog', 'Cane Paratore', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Shakira', 13, 'dog', 'Cane Paratore', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Zula', 11, 'dog', 'Lupo Italiano', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Brennon', 18, 'dog', 'Lupo Italiano', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Liana', 15, 'dog', 'Lupo Italiano', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Unique', 2, 'dog', 'Lupo Italiano', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Dedric', 9, 'dog', 'Lupo Italiano', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Diego', 8, 'dog', 'Lupo Italiano', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Mike', 2, 'dog', 'Maremmano-Abruzzese Sheepdog', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Meaghan', 18, 'dog', 'Maremmano-Abruzzese Sheepdog', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Berniece', 1, 'dog', 'Maremmano-Abruzzese Sheepdog', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Yessenia', 16, 'dog', 'Maremmano-Abruzzese Sheepdog', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Janet', 4, 'dog', 'Maremmano-Abruzzese Sheepdog', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Giuseppe', 10, 'dog', 'Maremmano-Abruzzese Sheepdog', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Laney', 18, 'dog', 'Maremmano-Abruzzese Sheepdog', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Christophe', 11, 'dog', 'Maremmano-Abruzzese Sheepdog', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Holly', 18, 'dog', 'Maremmano-Abruzzese Sheepdog', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Kip', 9, 'dog', 'Maremmano-Abruzzese Sheepdog', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Oren', 11, 'dog', 'Maremmano-Abruzzese Sheepdog', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Queen', 4, 'dog', 'Maremmano-Abruzzese Sheepdog', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Kianna', 2, 'dog', 'Maremmano-Abruzzese Sheepdog', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Mariane', 16, 'dog', 'Cane Paratore', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Talia', 8, 'dog', 'Cane Paratore', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Dave', 10, 'dog', 'Cane Paratore', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Adelbert', 5, 'dog', 'Cane Paratore', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Ronaldo', 13, 'dog', 'Cane Paratore', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Edythe', 6, 'dog', 'Cane Paratore', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Charlene', 18, 'dog', 'Cane Paratore', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Lurline', 20, 'dog', 'Cane Paratore', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Madelynn', 18, 'dog', 'Cane Paratore', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Ignacio', 9, 'dog', 'Cane Paratore', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Lucinda', 2, 'dog', 'Cane Paratore', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Audreanne', 11, 'dog', 'Cane Paratore', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Rasheed', 19, 'dog', 'Cane Paratore', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Deshawn', 12, 'dog', 'West Highland White Terrier', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Alphonso', 12, 'dog', 'West Highland White Terrier', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Maxie', 11, 'dog', 'West Highland White Terrier', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Rupert', 16, 'dog', 'West Highland White Terrier', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Jerrell', 8, 'dog', 'West Highland White Terrier', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Xander', 9, 'dog', 'West Highland White Terrier', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Kelton', 9, 'dog', 'West Highland White Terrier', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Etha', 20, 'dog', 'West Highland White Terrier', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Reba', 11, 'dog', 'West Highland White Terrier', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Eliseo', 18, 'dog', 'West Highland White Terrier', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Freeman', 1, 'dog', 'West Highland White Terrier', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Deshaun', 9, 'dog', 'West Highland White Terrier', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Jane', 14, 'dog', 'West Highland White Terrier', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Garrick', 20, 'dog', 'West Highland White Terrier', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Zachary', 14, 'cat', 'Chausie', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Keon', 8, 'cat', 'Chausie', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Lisa', 14, 'cat', 'Chausie', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Ashley', 6, 'cat', 'Chausie', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Rowan', 20, 'cat', 'Chausie', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Jessyca', 20, 'cat', 'Chausie', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Tess', 3, 'cat', 'Chausie', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Josefa', 4, 'cat', 'Chausie', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Janae', 2, 'cat', 'American Bobtail', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Darby', 3, 'cat', 'American Bobtail', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Vernie', 4, 'cat', 'American Bobtail', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Vernon', 16, 'cat', 'American Bobtail', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Barbara', 6, 'cat', 'American Bobtail', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Natalie', 10, 'cat', 'American Bobtail', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Miguel', 8, 'cat', 'American Bobtail', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Henry', 3, 'cat', 'American Bobtail', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Kara', 17, 'cat', 'American Bobtail', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Dante', 13, 'snake', 'Black headed python', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Brandon', 20, 'snake', 'Black headed python', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Janessa', 17, 'snake', 'Black headed python', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Bethel', 10, 'snake', 'Black headed python', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Katlynn', 10, 'snake', 'Black headed python', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Amanda', 1, 'snake', 'Black headed python', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Hildegard', 5, 'snake', 'Rhinoceros viper', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Gerson', 10, 'snake', 'Rhinoceros viper', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Yasmin', 10, 'snake', 'Rhinoceros viper', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Kailey', 3, 'snake', 'Rhinoceros viper', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Albina', 7, 'snake', 'Rhinoceros viper', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Rodolfo', 5, 'snake', 'Rhinoceros viper', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Heloise', 1, 'snake', 'Rhinoceros viper', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Boris', 18, 'snake', 'Banded pitviper', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Marcelle', 3, 'snake', 'Banded pitviper', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Grace', 3, 'snake', 'Banded pitviper', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Kaya', 18, 'snake', 'Banded pitviper', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Olga', 2, 'snake', 'Banded pitviper', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Nyasia', 5, 'snake', 'Banded pitviper', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Ivah', 20, 'snake', 'Banded pitviper', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Hollie', 8, 'snake', 'Banded pitviper', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Deon', 7, 'horse', 'Cerbat Mustang', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Fabian', 2, 'horse', 'Cerbat Mustang', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Jacynthe', 6, 'horse', 'Cerbat Mustang', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Jana', 13, 'horse', 'Cerbat Mustang', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Graciela', 12, 'horse', 'Cerbat Mustang', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Eladio', 2, 'horse', 'Cerbat Mustang', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Pansy', 5, 'horse', 'Cerbat Mustang', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Janie', 2, 'horse', 'Cerbat Mustang', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Genevieve', 19, 'horse', 'Byelorussian Harness Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Buford', 17, 'horse', 'Byelorussian Harness Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Jensen', 2, 'horse', 'Byelorussian Harness Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Martina', 15, 'horse', 'Byelorussian Harness Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Maida', 5, 'horse', 'Byelorussian Harness Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Sophie', 14, 'horse', 'Byelorussian Harness Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Cornell', 20, 'horse', 'Byelorussian Harness Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Murray', 8, 'horse', 'Byelorussian Harness Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Danial', 12, 'horse', 'Byelorussian Harness Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Marlee', 19, 'horse', 'Byelorussian Harness Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Johathan', 20, 'horse', 'Byelorussian Harness Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Maurice', 9, 'horse', 'Byelorussian Harness Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Andreane', 3, 'horse', 'Byelorussian Harness Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Sarai', 2, 'horse', 'Byelorussian Harness Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Kara', 2, 'horse', 'Cavallo Romano della Maremma Laziale', false);       
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Erick', 2, 'horse', 'Cavallo Romano della Maremma Laziale', true);       
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Monserrat', 14, 'horse', 'Cavallo Romano della Maremma Laziale', false); 
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Hosea', 19, 'horse', 'Cavallo Romano della Maremma Laziale', true);      
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Reggie', 3, 'horse', 'Cavallo Romano della Maremma Laziale', false);     
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Leonor', 12, 'horse', 'Cavallo Romano della Maremma Laziale', true);     
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Lillian', 15, 'horse', 'Noriker Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Brielle', 13, 'horse', 'Noriker Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Myrtie', 9, 'horse', 'Noriker Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Arvilla', 6, 'horse', 'Noriker Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Alejandra', 20, 'horse', 'Noriker Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Vicky', 11, 'horse', 'Noriker Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Favian', 8, 'horse', 'Noriker Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Kitty', 17, 'horse', 'Noriker Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Hoyt', 3, 'horse', 'Noriker Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Gustave', 9, 'horse', 'Murakoz Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Ransom', 4, 'horse', 'Murakoz Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Mack', 9, 'horse', 'Murakoz Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Ethelyn', 16, 'horse', 'Murakoz Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Marcellus', 12, 'horse', 'Murakoz Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Lizeth', 3, 'horse', 'Murakoz Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Ian', 2, 'horse', 'Murakoz Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Elvis', 4, 'horse', 'Murakoz Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Salvador', 12, 'horse', 'Murakoz Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Rosamond', 7, 'horse', 'Murakoz Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Velma', 11, 'horse', 'Murakoz Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Zoey', 6, 'horse', 'Murakoz Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Julie', 12, 'horse', 'Murakoz Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Carissa', 19, 'horse', 'Murakoz Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Sherwood', 13, 'horse', 'Baluchi Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Grady', 5, 'horse', 'Baluchi Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Brando', 7, 'horse', 'Baluchi Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Jessyca', 15, 'horse', 'Baluchi Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Avis', 17, 'horse', 'Baluchi Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Gabrielle', 3, 'horse', 'Baluchi Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Oran', 6, 'horse', 'Baluchi Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Jorge', 8, 'horse', 'Baluchi Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Dennis', 4, 'horse', 'Baluchi Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Horacio', 16, 'horse', 'Baluchi Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Eusebio', 7, 'horse', 'Baluchi Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Eleonore', 14, 'horse', 'Baluchi Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Ada', 14, 'horse', 'Baluchi Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Adolphus', 7, 'horse', 'Baluchi Horse', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Princess', 4, 'horse', 'Baluchi Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Erik', 5, 'horse', 'Mangalarga Marchador', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Trystan', 4, 'horse', 'Mangalarga Marchador', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Randal', 20, 'horse', 'Mangalarga Marchador', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Leon', 15, 'horse', 'Mangalarga Marchador', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Roscoe', 4, 'horse', 'Mangalarga Marchador', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Cleveland', 2, 'horse', 'Mangalarga Marchador', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Don', 1, 'horse', 'Mangalarga Marchador', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Helene', 5, 'horse', 'Mangalarga Marchador', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Raina', 15, 'horse', 'Mangalarga Marchador', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Loraine', 3, 'horse', 'Mangalarga Marchador', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Elta', 5, 'horse', 'Mangalarga Marchador', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Esther', 7, 'horse', 'Mangalarga Marchador', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Meghan', 19, 'horse', 'Monterufolino', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Terrence', 17, 'horse', 'Monterufolino', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Wilford', 1, 'horse', 'Monterufolino', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Murl', 1, 'horse', 'Monterufolino', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Kirsten', 13, 'horse', 'Monterufolino', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Breana', 13, 'horse', 'Monterufolino', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Lawson', 17, 'horse', 'Monterufolino', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Camryn', 6, 'horse', 'Dongola Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Allene', 8, 'horse', 'Dongola Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Cleve', 14, 'horse', 'Dongola Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Hassan', 9, 'horse', 'Dongola Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Earl', 4, 'horse', 'Dongola Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Kane', 14, 'horse', 'Dongola Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Ferne', 11, 'horse', 'Dongola Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Hermann', 4, 'horse', 'Dongola Horse', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Aurelie', 9, 'bird', 'Bristle-thighed Curlew', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Jared', 1, 'bird', 'Bristle-thighed Curlew', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Alexis', 19, 'bird', 'Bristle-thighed Curlew', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Dakota', 12, 'bird', 'Bristle-thighed Curlew', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Mariela', 16, 'bird', 'Bristle-thighed Curlew', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Roxanne', 6, 'bird', 'Bristle-thighed Curlew', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Muhammad', 2, 'bird', 'Bristle-thighed Curlew', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Amely', 16, 'bird', 'Bristle-thighed Curlew', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Breana', 10, 'bird', 'White-tailed Eagle', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Giovanni', 14, 'bird', 'White-tailed Eagle', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Destany', 7, 'bird', 'White-tailed Eagle', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Brisa', 6, 'bird', 'White-tailed Eagle', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Margarett', 11, 'bird', 'White-tailed Eagle', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Curtis', 20, 'bird', 'White-tailed Eagle', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Alene', 15, 'bird', 'White-tailed Eagle', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Cordelia', 19, 'bird', 'White-tailed Eagle', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Marcellus', 8, 'bird', 'White-tailed Eagle', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Catherine', 20, 'bird', 'White-tailed Eagle', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Laurine', 18, 'bird', 'White-tailed Eagle', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Nasir', 13, 'bird', 'White-tailed Eagle', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Francisca', 12, 'bird', 'House Finch', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Name', 5, 'bird', 'House Finch', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Madyson', 11, 'bird', 'House Finch', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Johnathon', 14, 'bird', 'House Finch', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Abbey', 14, 'bird', 'House Finch', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Dave', 3, 'bird', 'Jabiru', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Angelita', 7, 'bird', 'Jabiru', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Leda', 15, 'bird', 'Jabiru', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Fay', 3, 'bird', 'Jabiru', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Elmore', 13, 'bird', 'Jabiru', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Bettye', 3, 'bird', 'Jabiru', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Braeden', 4, 'bird', 'Jabiru', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Taryn', 3, 'bird', 'Jabiru', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Green', 15, 'bird', 'Jabiru', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Cassandra', 14, 'bird', 'Jabiru', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Jalon', 15, 'bird', 'Jabiru', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Jordan', 19, 'bird', 'Eastern Towhee', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Heather', 3, 'bird', 'Eastern Towhee', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Arlene', 14, 'bird', 'Eastern Towhee', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Giles', 10, 'bird', 'Eastern Towhee', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Johnson', 17, 'bird', 'Eastern Towhee', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Neal', 20, 'bird', 'Eastern Towhee', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Arnoldo', 7, 'bird', 'Eastern Towhee', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Jazmin', 20, 'bird', 'Eastern Towhee', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Myrtle', 14, 'bird', 'Green-tailed Towhee', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Nestor', 14, 'bird', 'Green-tailed Towhee', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Unique', 8, 'bird', 'Green-tailed Towhee', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Marcella', 2, 'bird', 'Green-tailed Towhee', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Jennifer', 4, 'bird', 'Green-tailed Towhee', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Joan', 17, 'bird', 'Green-tailed Towhee', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Ethan', 9, 'bird', 'Green-tailed Towhee', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Maiya', 3, 'bird', 'Green-tailed Towhee', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Efren', 17, 'bird', 'Green-tailed Towhee', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Nat', 16, 'bird', 'Green-tailed Towhee', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Marquise', 11, 'bird', 'Green-tailed Towhee', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Deangelo', 20, 'bird', 'Green-tailed Towhee', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Therese', 3, 'bird', 'Green-tailed Towhee', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Brandy', 16, 'bird', 'Great-tailed Grackle', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Adrain', 8, 'bird', 'Great-tailed Grackle', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Elisa', 5, 'bird', 'Great-tailed Grackle', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Eladio', 9, 'bird', 'Great-tailed Grackle', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Elissa', 19, 'bird', 'Great-tailed Grackle', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Maggie', 19, 'bird', 'Great-tailed Grackle', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Nichole', 18, 'rabbit', 'Rhinelander', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Gladys', 7, 'rabbit', 'Rhinelander', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Walton', 19, 'rabbit', 'Rhinelander', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Lucious', 4, 'rabbit', 'Rhinelander', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Reva', 18, 'rabbit', 'Rhinelander', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Magali', 2, 'rabbit', 'Rhinelander', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Kailee', 10, 'rabbit', 'Rhinelander', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Drake', 11, 'rabbit', 'Rhinelander', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Mae', 15, 'rabbit', 'Rhinelander', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Steve', 9, 'rabbit', 'Rhinelander', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Rick', 10, 'rabbit', 'Rhinelander', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Florida', 20, 'rabbit', 'Rhinelander', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Jeff', 2, 'rabbit', 'Rhinelander', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Alessandro', 20, 'rabbit', 'Rhinelander', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Tod', 11, 'rabbit', 'English Angora', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Vergie', 13, 'rabbit', 'English Angora', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Eloisa', 12, 'rabbit', 'English Angora', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Hulda', 9, 'rabbit', 'English Angora', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Pablo', 17, 'rabbit', 'English Angora', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Gianni', 20, 'rabbit', 'English Angora', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Maureen', 16, 'rabbit', 'English Angora', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Enrico', 11, 'rabbit', 'English Angora', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Karelle', 19, 'rabbit', 'English Angora', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Ricardo', 12, 'rabbit', 'English Angora', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Opal', 17, 'rabbit', 'English Angora', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Cleo', 8, 'rabbit', 'English Angora', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Israel', 17, 'rabbit', 'Crème D’Argent', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Austin', 20, 'rabbit', 'Crème D’Argent', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Courtney', 5, 'rabbit', 'Crème D’Argent', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Yolanda', 12, 'rabbit', 'Crème D’Argent', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Janessa', 10, 'rabbit', 'Crème D’Argent', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Rickie', 6, 'rabbit', 'Crème D’Argent', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Kaia', 7, 'rabbit', 'Crème D’Argent', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Mac', 17, 'rabbit', 'Crème D’Argent', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Katlyn', 9, 'rabbit', 'Florida White', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Arely', 20, 'rabbit', 'Florida White', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Kevin', 19, 'rabbit', 'Florida White', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Ansley', 18, 'rabbit', 'Florida White', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Corbin', 19, 'rabbit', 'Florida White', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Jazmyne', 8, 'rabbit', 'Florida White', true);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Ralph', 15, 'rabbit', 'Florida White', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Yasmin', 16, 'rabbit', 'Florida White', false);
INSERT INTO pets (name, age, type, breed, microchip) VALUES('Joan', 4, 'rabbit', 'Florida White', true);